title: "[FOSDEM 2023] [CFP] Fast and Streaming Data DevRoom"
description: "Welcome to the first edition of the Fast and Streaming Data DevRoom at FOSDEM 2023.  Our DevRoom will be scheduled from 10:30 to 14:30 on Saturday February 4th. We will be accepting in-person talks only, with recordings for all the sessions."
theme: jekyll-theme-hacker
show_downloads: false
