title: "[FOSDEM 2025] [CFP] Data Analytics DevRoom"
description: "Welcome to the first edition of the Data Analytics DevRoom at FOSDEM.  Our DevRoom will be scheduled on Saturday, February 1st 2025. We will be accepting in-person talks only, with recordings for all the sessions."
theme: jekyll-theme-hacker
show_downloads: false
